### ISSUE TITLE
Identical prompts in released datasets

### ISSUE THREAD

**Issue by RaymondLi0** [amazon-science/recode#5]
In the released datasets, the prompts for different seeds are identical.
For example, there is no diff between `dataset-release/perturbed_finalized/humaneval/full/func_name/humaneval_FuncRenameButterFinger_s0.jsonl` and `dataset-release/perturbed_finalized/humaneval/full/func_name/humaneval_FuncRenameButterFinger_s1.jsonl`
Maybe I'm missing something, but I think these prompts are supposed to be different for random perturbations like this one?

**Comment by wshiqi-aws** [comment]
Hi Raymond, thanks for reporting this! There was a small mistake when cleaning up the code and releasing the dataset where random seeds were not passed correctly for the nlaugmenter of function rename perturbations. I have just updated released perturbed datasets and patched the perturbation code. Let me know if you see any other issues!

**Comment by RaymondLi0** [comment]
Awesome, thanks!!
